// src/components/IframeRenderer.vue
<script setup lang="ts">
import { ref, reactive, watch, onMounted, onUnmounted } from "vue"

const props = defineProps<{
  defaultUrl: string
  defaultWidth: string
  defaultHeight: string
  defaultOtherAttributes: Record<string, string>
  autoReload: boolean
  showMessageEvents: boolean
}>()
let url = ref(props.defaultUrl)
let width = ref(props.defaultWidth)
let height = ref(props.defaultHeight)
let otherAttributes = reactive(props.defaultOtherAttributes)
let autoReload = ref(props.autoReload)
let showMessageEventsRef = ref(props.showMessageEvents)
let iframekey = ref(1)

const updateURL = () => {
  const params = new URLSearchParams()
  if (autoReload.value) params.set("autoReload", "1")
  if (showMessageEventsRef.value) params.set("showMessageEvents", "1")
  params.set("url", url.value)
  params.set("width", width.value)
  params.set("height", height.value)
  params.set("otherAttributes", JSON.stringify(otherAttributes))
  const domain = new URL(window.location.href).origin
  window.history.replaceState({}, `Iframe tester: ${domain}`, `${window.location.pathname}?${params}`)
}

watch(url, updateURL)
watch(width, updateURL)
watch(height, updateURL)
watch(otherAttributes, updateURL)
watch(autoReload, updateURL)
watch(showMessageEventsRef, updateURL)

const iframeAttributes = ["frameborder", "allow", "csp", "importance", "loading", "name", "referrerpolicy", "sandbox", "srcdoc"]

let timer: number | null = null
if (autoReload.value && !timer) {
  timer = setInterval(() => {
    iframekey.value++
  }, 5000)
} else if (timer) {
  clearInterval(timer)
  timer = null
}

const receivedMessages = ref<any[]>([])

const handleMessage = (event: MessageEvent) => {
  // Potentially filter messages by origin here if needed
  // if (event.origin !== 'expected_origin') return;

  const suppress = event.data.type === "TIMER_TICK" || event.data.type === "TIMER_SYNC"
  if (suppress) return

  receivedMessages.value.unshift({
    data: event.data,
    origin: event.origin,
    timestamp: new Date().toLocaleTimeString()
  })
}

onMounted(() => {
  window.addEventListener('message', handleMessage)
})

onUnmounted(() => {
  window.removeEventListener('message', handleMessage)
  if (timer) {
    clearInterval(timer)
  }
})
</script>

<template>
  <div>
    <label for="checkbox">Auto-reload every 5s</label>
    <input type="checkbox" id="checkbox" v-model="autoReload" />
  </div>

  <input id="url" v-model="url" placeholder="URL here" />

  <div class="main-content">
    <iframe :key="iframekey" :width="width" :height="height" :src="url" v-bind="otherAttributes"></iframe>

    <div v-if="showMessageEventsRef" class="sidebar">
      <h3>Received Messages:</h3>
      <ul>
        <li v-for="(msg, index) in receivedMessages" :key="index">
          <pre><code>{{ JSON.stringify(msg, null, 2) }}</code></pre>
        </li>
      </ul>
      <button @click="receivedMessages = []" v-if="receivedMessages.length > 0">Clear Messages</button>
    </div>
  </div>

  <div>
    <p>Size:</p>
    <input v-model="width" placeholder="640px" />
    by
    <input v-model="height" placeholder="480px" />
  </div>

  <div>
    <label for="showMessages">Show Message Events</label>
    <input type="checkbox" id="showMessages" v-model="showMessageEventsRef" />
  </div>

  <div class="row">
    <div style="flex: 1; padding:10px;">
      <h3>Iframe custom Attributes:</h3>

      <div class="row">
        <ul>
          <li v-for="value in iframeAttributes">
            <p>
              <code>
                <a :href="`https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#${value}`">{{ value }}</a></code
              >
            </p>
            <input v-model="otherAttributes[value]" placeholder="" />
          </li>
        </ul>
      </div>
    </div>

    <div style="flex: 1;padding:10px;">
      <h3>Code:</h3>

      <pre>
        <code>
    &lt;iframe
    width="{{width}}"
    height="{{height}}"
    src="{{url}}"
    {{Object.entries(otherAttributes).map(([key, value]) => `${key}="${value}"`).join(" ")}}
    &gt;&lt;/iframe&gt;
        </code>
      </pre>
    </div>
  </div>
</template>

<style scoped>
h1 {
  font-weight: 500;
  font-size: 2.6rem;
  position: relative;
  top: -10px;
}

h3 {
  font-size: 1.2rem;
  margin-top: 50px;
  margin-bottom: 0px;
}

iframe {
  margin-top: 12px;
  margin-bottom: 36px;
  flex-grow: 1; /* Allow iframe to grow */
  margin-right: 20px; /* Space between iframe and sidebar */
}

input#url {
  font-size: x-large;
  width: 100%;
}

input[type="checkbox"] {
  margin: 0 8px;
}

div.row {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.main-content {
  display: flex;
  flex-direction: row;
  align-items: flex-start; /* Align items at the top */
}

.sidebar {
  width: 360px; /* Adjust width as needed */
  border-left: 1px solid #ccc;
  padding-left: 20px;
  height: calc(100vh - 200px); /* Adjust height based on your layout */
  overflow-y: auto;
}

.sidebar h3 {
  margin-top: 0;
}

.sidebar ul {
  list-style: none;
  padding: 0;
}

.sidebar li {
  margin-bottom: 10px;
  border-bottom: 1px dashed #eee;
  padding-bottom: 10px;
}

.sidebar pre {
  white-space: pre-wrap; /* Wrap long lines */
  word-break: break-all; /* Break words if needed */
  background-color: #f5f5f5;
  padding: 5px;
  border-radius: 4px;
  font-size: 12px;
}
</style>

// src/components/IframeRenderer.tsx
import { useState, useEffect, useRef } from "react"
import "./IframeRenderer.css"

interface IframeRendererProps {
  defaultUrl: string
  defaultWidth: string
  defaultHeight: string
  defaultOtherAttributes: Record<string, string>
  autoReload: boolean
  showMessageEvents: boolean
}

interface ReceivedMessage {
  data: any
  origin: string
  timestamp: string
}

export default function IframeRenderer(props: IframeRendererProps) {
  const [url, setUrl] = useState(props.defaultUrl)
  const [width, setWidth] = useState(props.defaultWidth)
  const [height, setHeight] = useState(props.defaultHeight)
  const [otherAttributes, setOtherAttributes] = useState(props.defaultOtherAttributes)
  const [autoReload, setAutoReload] = useState(props.autoReload)
  const [showMessageEventsRef, setShowMessageEventsRef] = useState(props.showMessageEvents)
  const [iframekey, setIframekey] = useState(1)
  const [receivedMessages, setReceivedMessages] = useState<ReceivedMessage[]>([])
  const [eventsSidebarOpen, setEventsSidebarOpen] = useState(false)
  const timerRef = useRef<number | null>(null)

  const iframeAttributes = [
    { name: "allow", description: "Specifies a Permissions Policy for the iframe (e.g., 'camera; microphone')" },
    { name: "allowfullscreen", description: "Set to true to allow the iframe to activate fullscreen mode" },
    { name: "loading", description: "Indicates how the browser should load the iframe (eager or lazy)" },
    { name: "name", description: "A targetable name for the embedded browsing context" },
    { name: "referrerpolicy", description: "Controls which referrer is sent when fetching the iframe's resource" },
    { name: "sandbox", description: "Applies extra restrictions to the content in the frame" },
    { name: "srcdoc", description: "Inline HTML to embed, overriding the src attribute" }
  ]

  const updateURL = () => {
    const params = new URLSearchParams()
    if (autoReload) params.set("autoReload", "1")
    if (showMessageEventsRef) params.set("showMessageEvents", "1")
    params.set("url", url)
    params.set("width", width)
    params.set("height", height)
    params.set("otherAttributes", JSON.stringify(otherAttributes))
    const domain = new URL(window.location.href).origin
    window.history.replaceState({}, `Iframe tester: ${domain}`, `${window.location.pathname}?${params}`)
  }

  useEffect(() => {
    updateURL()
  }, [url, width, height, otherAttributes, autoReload, showMessageEventsRef])

  useEffect(() => {
    if (autoReload && !timerRef.current) {
      timerRef.current = window.setInterval(() => {
        setIframekey((prev) => prev + 1)
      }, 5000)
    } else if (!autoReload && timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }

    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current)
      }
    }
  }, [autoReload])

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      const suppress = event.data.type === "TIMER_TICK" || event.data.type === "TIMER_SYNC"
      if (suppress) return

      setReceivedMessages((prev) => [
        {
          data: event.data,
          origin: event.origin,
          timestamp: new Date().toLocaleTimeString()
        },
        ...prev
      ])
    }

    window.addEventListener("message", handleMessage)

    return () => {
      window.removeEventListener("message", handleMessage)
    }
  }, [])

  const handleAttributeChange = (key: string, value: string) => {
    setOtherAttributes((prev) => ({
      ...prev,
      [key]: value
    }))
  }

  const handleMouseDown = (direction: "top" | "right" | "bottom" | "left") => (e: React.MouseEvent) => {
    e.preventDefault()
    const startX = e.clientX
    const startY = e.clientY
    const startWidth = parseInt(width)
    const startHeight = parseInt(height)

    const handleMouseMove = (e: MouseEvent) => {
      const deltaX = e.clientX - startX
      const deltaY = e.clientY - startY

      if (direction === "right") {
        setWidth(`${Math.max(100, startWidth + deltaX)}px`)
      } else if (direction === "left") {
        setWidth(`${Math.max(100, startWidth - deltaX)}px`)
      } else if (direction === "bottom") {
        setHeight(`${Math.max(100, startHeight + deltaY)}px`)
      } else if (direction === "top") {
        setHeight(`${Math.max(100, startHeight - deltaY)}px`)
      }
    }

    const handleMouseUp = () => {
      document.removeEventListener("mousemove", handleMouseMove)
      document.removeEventListener("mouseup", handleMouseUp)
    }

    document.addEventListener("mousemove", handleMouseMove)
    document.addEventListener("mouseup", handleMouseUp)
  }

  return (
    <>
      <header className="page-header">
        <h1>iframe tester</h1>
        <p>Enter a URL to set as the iframe, all possible params are saved into the URL so you can refresh/share.</p>
      </header>
      <div className="container">
        <div className="sidebar">
        <div className="sidebar-section">
          <label htmlFor="url-input">URL:</label>
          <input id="url-input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="Enter iframe URL" />
        </div>

        <div className="sidebar-section">
          <label>Size:</label>
          <div className="size-inputs">
            <input value={width} onChange={(e) => setWidth(e.target.value)} placeholder="640px" />
            <span>×</span>
            <input value={height} onChange={(e) => setHeight(e.target.value)} placeholder="480px" />
          </div>
        </div>

        <div className="sidebar-section">
          <label htmlFor="auto-reload">
            <input type="checkbox" id="auto-reload" checked={autoReload} onChange={(e) => setAutoReload(e.target.checked)} />
            Auto-reload every 5s
          </label>
        </div>

        <div className="sidebar-section">
          <h3>Iframe Attributes:</h3>
          <div className="attributes-list">
            {iframeAttributes.map((attr) => (
              <div key={attr.name} className="attribute-item">
                <label>
                  <a href={`https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#${attr.name}`} target="_blank" rel="noopener noreferrer">
                    {attr.name}
                  </a>
                </label>
                <p className="attribute-description">{attr.description}</p>
                <input value={otherAttributes[attr.name] || ""} onChange={(e) => handleAttributeChange(attr.name, e.target.value)} placeholder="" />
              </div>
            ))}
          </div>
        </div>

        <div className="sidebar-section code-section">
          <h3>Code:</h3>
          <pre>
            <code>
              {`<iframe
  width="${width}"
  height="${height}"
  src="${url}"${Object.entries(otherAttributes).filter(([, value]) => value).length > 0 ? '\n  ' : ''}${Object.entries(otherAttributes)
                .filter(([, value]) => value)
                .map(([key, value]) => `${key}="${value}"`)
                .join('\n  ')}
></iframe>`}
            </code>
          </pre>
        </div>
      </div>

      <div className="main-content">
        <div className="iframe-container">
          <iframe key={iframekey} width={width} height={height} src={url} {...otherAttributes}></iframe>
          <div className="resize-handle resize-handle-top" onMouseDown={handleMouseDown("top")}></div>
          <div className="resize-handle resize-handle-right" onMouseDown={handleMouseDown("right")}></div>
          <div className="resize-handle resize-handle-bottom" onMouseDown={handleMouseDown("bottom")}></div>
          <div className="resize-handle resize-handle-left" onMouseDown={handleMouseDown("left")}></div>
        </div>
      </div>

      <div className={`events-sidebar ${eventsSidebarOpen ? 'open' : ''}`}>
        <div className="events-sidebar-toggle" onClick={() => setEventsSidebarOpen(!eventsSidebarOpen)}>
          <span className="events-label">EVENTS</span>
        </div>
        {eventsSidebarOpen && (
          <div className="events-sidebar-content">
            <div className="events-sidebar-header">
              <h3>Received Messages</h3>
              {receivedMessages.length > 0 && (
                <button className="clear-button" onClick={() => setReceivedMessages([])}>
                  Clear
                </button>
              )}
            </div>
            <div className="events-list">
              {receivedMessages.length === 0 ? (
                <p className="no-events">No events received yet</p>
              ) : (
                <ul>
                  {receivedMessages.map((msg, index) => (
                    <li key={index}>
                      <pre>
                        <code>{JSON.stringify(msg, null, 2)}</code>
                      </pre>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
    </>
  )
}
